version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - public-data:/${APP_NAME:-app}/public
      - tmp-data:/${APP_NAME:-app}/tmp
    command: nginx -g 'daemon off;' -c /etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      APP_NAME: ${APP_NAME:-app}
    depends_on:
      - app

  app: &app
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME:-app}
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/${APP_NAME:-app}
      - bundle-data:/usr/local/bundle
      - public-data:/${APP_NAME:-app}/public
      - tmp-data:/${APP_NAME:-app}/tmp
      - log-data:/${APP_NAME:-app}/log
    depends_on:
      - db
    stdin_open: true
    tty: true

  webpacker:
    <<: *app
    command: bash -c "./bin/webpack-dev-server"
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"

volumes:
  mysql-data:
  bundle-data:
  public-data:
  tmp-data:
  log-data:
