version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - public-data:/${APP_NAME:-app}/public
      - tmp-data:/${APP_NAME:-app}/tmp
    command: nginx -g 'daemon off;' -c /etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      APP_NAME: ${APP_NAME:-app}
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME:-app}
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/${APP_NAME:-app}
      - bundle-data:/usr/local/bundle
      - node_modules-data:/${APP_NAME:-app}/node_modules
      - public-data:/${APP_NAME:-app}/public
      - tmp-data:/${APP_NAME:-app}/tmp
      - log-data:/${APP_NAME:-app}/log
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  redis:
    build:
      context: redis
    volumes:
      - ./redis:/usr/local/etc/redis
      - redis-data:/data
    command: redis-server
    ports:
      - "6379:6379"

  webpacker:
    build: .
    working_dir: /webpacker
    command: ./bin/webpack-dev-server
    volumes:
      - .:/webpacker
      - public-data:/webpacker/public
      - bundle-data:/usr/local/bundle
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    stdin_open: true
    tty: true
    depends_on:
      - app

volumes:
  mysql-data:
  bundle-data:
  node_modules-data:
  public-data:
  tmp-data:
  log-data:
  redis-data:
