name: Docker-CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
          Build & Yarn Setup
          # package.jsonのパッケージのバージョンとハッシュ値をyarn.lockのものと一致させる
        run: |
          docker-compose run web yarn install --check-files
          docker-compose run web yarn upgrade
      - name: Bundle install
        run: |
          docker-compose run web bundle install
      - name: DB Create
        run: |
          docker-compose run web rails db:create
        env:
          RAILS_ENV: test
      - name: Run RSpec
        run: |
          docker-compose run web rspec
        env:
          RAILS_ENV: test
      - name: Compose Up
        run: |
          docker-compose up -d
      - name: Compose Down
        run: |
          docker-compose down
