name: DOCKER_CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        run: |
          docker-compose run web yarn install --check-files
          docker-compose run web yarn upgrade
        env:
          RAILS_ENV: test
      - name: Build
        run: |
          docker-compose build
        env:
          RAILS_ENV: test
      - name: DB Create
        run: |
          docker-compose run web rails db:create
        env:
          RAILS_ENV: test
      - name: Run RSpec
        run: |
          docker-compose run web rspec
      - name: Compose Up
        run: |
          docker-compose up
      - name: Compose Down
        run: |
          docker-compose down
