name: docker-compose-checker

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker-compose build
      - name: Compose-Up
        run: |
          docker-compose up -d
      - name: Compose-Down
        run: |
          docker-compose down
          docker-compose up -d
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rails-Test
        run: |
          docker-compose run web bundle exec rails db:create RAILS_ENV=test
